### ISSUE TITLE
module dependency ffilib.py not found

### ISSUE THREAD

**Issue by sidtupper** [matthias-bs/loraE22#7]
Hi,

the error: 
pi@RPiZero:~/loraE22/examples $ python testRecvE22_P2P.py
Traceback (most recent call last):
  File "/home/pi/loraE22/examples/testRecvE22_P2P.py", line 12, in <module>
    from loraE22 import ebyteE22
  File "/home/pi/loraE22/examples/loraE22.py", line 114, in <module>
    from machine import Pin, UART
  File "/home/pi/.local/lib/python3.9/site-packages/machine/__init__.py", line 1, in <module>
    from .timer import *
  File "/home/pi/.local/lib/python3.9/site-packages/machine/timer.py", line 1, in <module>
    import ffilib
  File "/home/pi/.local/lib/python3.9/site-packages/ffilib.py", line 2, in <module>
    import ffi
ModuleNotFoundError: No module named 'ffi'

environment:
pi@RPiZero:~/loraE22/examples $ hostnamectl
   Static hostname: RPiZero
         Icon name: computer
        Machine ID: aad00e19021a4953b77b7adbc5d1f0e9
           Boot ID: a3145e236d19460fa9ee5833c60034b4
  Operating System: Raspbian GNU/Linux 11 (bullseye)
            Kernel: Linux 6.1.21+
      Architecture: arm

Thanks for making this library.

**Comment by matthias-bs** [comment]
Hi,

This module is for [MicroPython](https://micropython.org/) (not for common Python).

**Comment by sidtupper** [comment]
A ha! Thanks. SidOn Dec 20, 2023, at 9:44 PM, Matthias Prinke ***@***.***> wrote:﻿
Hi,
This module is for MicroPython (not for common Python).
